### ISSUE TITLE
Implict declarations of functions

### ISSUE THREAD

**Issue by su8** [Duncaen/lobase#1]
![2017-12-25-020604_934x95_scrot](https://user-images.githubusercontent.com/29376083/34330172-fa315bd8-e918-11e7-829f-cc1369f5997a.png)

![2017-12-25-020946_955x318_scrot](https://user-images.githubusercontent.com/29376083/34330202-5babe572-e919-11e7-9a74-31a53aac8a5a.png)

**Comment by Duncaen** [comment]
Which system, libc and compiler are you using?
`stdlib.h` is included in both files, I'm wondering if its related to using `#include_next` in the compat headers.

**Comment by su8** [comment]
Gentoo, glibc, clang 3.9.1 and gcc 5.4.0-r3

**Comment by mfasold** [comment]
Same issue here when trying to build under Debian stretch (with gcc 6.3.0).

**Comment by Duncaen** [comment]
Thanks for reporting, a debian environment to test was easier to setup, this should be fixed by 3a8a0090efee2441977b042a38ddca54067f8b20.

**Comment by mfasold** [comment]
Many thanks for your quick help! Indeed, I could compile a large number of sources. However, i got stuck at the first linker step
```
gcc -o bc bc.o scan.o tty.o dc.o bcode.o inout.o mem.o stack.o -ledit -lcurses -lcrypto
bc.o: In function `yyerror':
/data/obj/usr.bin/bc/../../..//usr.bin/bc/bc.y:954: undefined reference to `yyin'
```
One should be able to reproduce this in a debian:stretch container.

**Comment by Duncaen** [comment]
You need to install flex and run `./configure` again.
I'm going improve the configure script to fail if some of the dependencies are not found.

**Comment by mfasold** [comment]
Ok, many thanks. I managed to build everything.

Along the way, compilation of `find` did not succeed due to the following
```
error: 'ARG_MAX' undeclared (first use in this function)
```
which I got by with [this fix](http://lists.openembedded.org/pipermail/openembedded-devel/2008-April/050418.html).

**Comment by Duncaen** [comment]
Fixed this in commit 5dcb7d6e947d5e24baad9b61fc4e5473e65777bf.

**Comment by su8** [comment]
Well done @Duncaen !

Closing this issue as you fixed the implict declarations of functions.

Can I suggest simple version of `uname.c` ?

```c
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/utsname.h>

#define MAX_STRING_SIZE 1024

int main(int argc, char *argv[]) {
  int ch = 0;
  char buf[MAX_STRING_SIZE];
  char *all = buf;
  struct utsname KerneL;

  memset(&KerneL, 0, sizeof(struct utsname));

  if (-1 == (uname(&KerneL))) {
    fprintf(stderr, "%s\n", "uname() failed");
    return EXIT_FAILURE;
  }

  if (1 == argc) {
    puts(KerneL.sysname);
  }

  while (-1 != (ch = getopt(argc, argv, "asnrvm"))) {
    switch(ch) {
      case 'a':
        all += snprintf(all, MAX_STRING_SIZE-1, "%s %s %s %s %s ",
            KerneL.sysname, KerneL.nodename, KerneL.release,
            KerneL.version, KerneL.machine);
        break;
      case 's':
        all += snprintf(all, MAX_STRING_SIZE-1, "%s ", KerneL.sysname);
        break;
      case 'n':
        all += snprintf(all, MAX_STRING_SIZE-1, "%s ", KerneL.nodename);
        break;
      case 'r':
        all += snprintf(all, MAX_STRING_SIZE-1, "%s ", KerneL.release);
        break;
      case 'v':
        all += snprintf(all, MAX_STRING_SIZE-1, "%s ", KerneL.version);
        break;
      case 'm':
        all += snprintf(all, MAX_STRING_SIZE-1, "%s ", KerneL.machine);
        break;
    }
  }

  *(--all) = '\0';
  puts(buf);

  return EXIT_SUCCESS;
}
```

**Comment by Duncaen** [comment]
`uname(1)` is already there, but I think it was never installed by `make install` because of the issue in de407b0da49e852fdfa5c76fae3e1d79ef76d39c.
