### ISSUE TITLE
Installation with prefix ignored

### ISSUE THREAD

**Issue by su8** [Duncaen/lobase#3]
When using `./configure --prefix=/tmp` it gets ignored by **bsd.own.mk** as it overrides the destination of the man pages with **/usr/share** instead. Same goes for **libopenbsd.a**

![2018-03-20-191146_1920x1080_scrot](https://user-images.githubusercontent.com/29376083/37674628-9ed5bef2-2c73-11e8-94e0-951bfac58a9a.png)

**Comment by Duncaen** [comment]
I pushed a commit that uses the directories from configure.
One small "problem" is that both `bin` and `usr.bin` goes into `${prefix}/bin`, but I think thats ok for now.

configure has no concept of multiple `bin` directories as far as I know.
I could add a new configure option later that allows to bin and sbin without prefix.
